import assert from "node:assert/strict";
import { test } from "node:test";

import { why, whyText, records, init } from "../dist/index.js";

const LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"foo@workspace:.":
  version: 0.0.0-use.local
  resolution: "foo@workspace:."
  dependencies:
    foolib: 1.2.3 || ^2.0.0
    buzz: "npm:^1.1.1"
  languageName: unknown
  linkType: soft

"foolib@npm:1.2.3 || ^2.0.0":
  version: 2.0.0
  resolution: "foolib@npm:2.0.0"
  dependencies:
    buzz: "npm:^1.1.1"
  checksum: 123061e52a0b3792c6a0472bf48ca6c337ccb58e92261049e7727a12c326b9627537e2ef8cb4453354d02c763b87c8b516f4eedfad99945c308927285bbc12ba
  languageName: node
  linkType: hard

"buzz@npm:^1.1.1":
  version: 1.1.2
  resolution: "buzz@npm:1.1.2"
  checksum: 58e92261049e7727a12c326b9627537e123061e52a0b3792c6a0472bf48ca6c337ccb2ef8cb4453354d02c763b87c8b516f4eedfad99945c308927285bbc12ba
  languageName: node
  linkType: hard
`;

test("init() is idempotent", async () => {
  await init();
  await init();
});

test("why() returns the paths to a package, with it as the leaf", async () => {
  // foolib is a direct dependency of the workspace root, which gets collapsed
  assert.deepEqual(await why(LOCK, "foolib"), [
    { descriptor: ["foolib", "1.2.3 || ^2.0.0"], version: "2.0.0" },
  ]);

  // buzz is reached twice: directly, and through foolib
  assert.deepEqual(await why(LOCK, "buzz"), [
    { descriptor: ["buzz", "^1.1.1"], version: "1.1.2" },
    {
      descriptor: ["foolib", "1.2.3 || ^2.0.0"],
      version: "2.0.0",
      children: [{ descriptor: ["buzz", "^1.1.1"], version: "1.1.2" }],
    },
  ]);
});

test("why() strips the npm: protocol from descriptors", async () => {
  // the lockfile spells this dependency "npm:^1.1.1"
  const tree = await why(LOCK, "buzz");
  assert.equal(tree[0].descriptor[1], "^1.1.1");
});

test("why() returns [] for a package that is not there", async () => {
  assert.deepEqual(await why(LOCK, "nope"), []);
});

test("why() honours a semver range", async () => {
  assert.notDeepEqual(await why(LOCK, "buzz", { range: "^1.0.0" }), []);
  assert.deepEqual(await why(LOCK, "buzz", { range: ">=9.0.0" }), []);
});

test("why() honours maxDepth", async () => {
  const deep = await why(LOCK, "buzz", { noMaxDepth: true });
  const shallow = await why(LOCK, "buzz", { maxDepth: 1 });
  assert.ok(JSON.stringify(shallow).length < JSON.stringify(deep).length);
});

test("whyText() renders the tree the CLI prints", async () => {
  assert.equal(
    await whyText(LOCK, "buzz"),
    "├─ buzz@1.1.2 (via ^1.1.1)\n" +
      "│\n" +
      "└─ foolib@2.0.0 (via 1.2.3 || ^2.0.0)\n" +
      "   └─ buzz@1.1.2 (via ^1.1.1)\n",
  );
});

test("whyText() returns undefined for a package that is not there", async () => {
  assert.equal(await whyText(LOCK, "nope"), undefined);
});

test("records() lists every descriptor", async () => {
  assert.deepEqual(await records(LOCK), [
    { name: "foo", version: "0.0.0-use.local", descriptor: "." },
    { name: "foolib", version: "2.0.0", descriptor: "1.2.3 || ^2.0.0" },
    { name: "buzz", version: "1.1.2", descriptor: "^1.1.1" },
  ]);
});

test("a malformed lockfile rejects rather than returning junk", async () => {
  await assert.rejects(() => why("this is not a yarn.lock", "foo"));
});

test("an invalid range rejects", async () => {
  await assert.rejects(() => why(LOCK, "buzz", { range: "not-a-range" }));
});
