[package]
version = "0.1.0"
name = "yarn-why"
description = "yarn why, but fast"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
homepage = "https://github.com/riquito/yarn-why"
edition = "2021"
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.57"
atty = "0.2.14"
pico-args = "0.4.2"
yarn-lock-parser = { git = "https://github.com/riquito/yarn-lock-parser", branch = "support-yarn-v2-or-greater" }

[dev-dependencies]
assert_cmd = "2.0.4"

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1
