[package]
name = "yarn-why"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
atty = "0.2.14"
pico-args = "0.4.2"
yarn-lock-parser = { git = "https://github.com/riquito/yarn-lock-parser", branch = "parse-dependencies" }
